---
apiVersion: v1
kind: Service
metadata:
  name: papergraph-postgres
  labels:
    app: papergraph
spec:
  ports:
    - port: 5432
  selector:
    app: papergraph
    tier: postgres
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: papergraph
spec:
  storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: papergraph-postgres
  labels:
    app: papergraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papergraph
      tier: postgres
  template:
    metadata:
      labels:
        app: papergraph
        tier: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      containers:
        - name: postgres
          image: postgres:12
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: data
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: papergraph-cred
                  key: postgres-password
            - name: POSTGRES_DB
              value: papergraph
            - name: POSTGRES_USER
              value: papergraph