
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: papergraph-run-
spec:
  entrypoint: run
  arguments:
    parameters:
    - name: cmd
      value: diesel print-schema

  templates:
  - name: run
    inputs:
      parameters:
      - name: cmd
    script:
      image: dennybritz/papergraph:latest
      env:
        - name: RUST_LOG
          value: info
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: papergraph-cred
              key: postgres-password
        - name: DATABASE_URL
          value: postgres://papergraph:$(POSTGRES_PASSWORD)@papergraph-postgres:5432/papergraph
      command: ["/bin/bash"]
      source: |
        {{inputs.parameters.cmd}}
